#!/bin/bash

REPO_NAME="$(basename "$PWD")"

USER=git config --get user.name

GH_REPO_LINK="https://github.com/$USER/$REPO_NAME.git"

echo $GH_REPO_LINK

VISIBILITY="--public"

git status -sbv 2>/dev/null

echo -e "\nCTRL + C to cancel\n"

read -p "Do you want to create this folder Repo in Github y/n : " opt

   case $opt in
     y | Y | yes | YES)

       gh repo create "$REPO_NAME" "${2:-$VISIBILITY}" 2>/dev/null
       echo -e "\n :::::: Repo created ${2:-$VISIBILITY}ly in Github ::::::\n"
       ;;

     *) echo "Proceeding without repo Creation at Github" ;;

    esac

git init 2>/dev/null

git checkout -b master 2>/dev/null || git checkout master 2>/dev/null

git add "${1:--u}" && git status -sbv

echo -e "\n :::::: ${1:-Only Modified Added } ::::::\n"

read -p "Commit message :  " commitMsg

git commit -m "$commitMsg"

git remote add origin "$GH_REPO_LINK" 2>/dev/null

git push -u origin master  \
|| git push --force -u origin master \
|| echo Changes committed but code not pushed to Github