#!/bin/bash

if [ -z "$1" ]; then
    # If $1 is not provided, read input from user
    read -p "Question :-  " userInput
else
    # If $1 is provided, use its value
    userInput="$@"
    echo Qusetion :- $userInput
fi
echo -e "\nMETA AI :-  "
tgpt --provider=duckduckgo --model=meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo -q "$userInput" | glow
