#!/bin/bash

if [ -z "$1" ]; then
    # If $1 is not provided, read input from user
    read -p "Question :-  " userInput
else
    # If $1 is provided, use its value
    userInput="$@"
    echo Qusetion :- $userInput
fi
echo -e "\nmistralai/Mixtral AI :-  "
tgpt --provider=duckduckgo --model=mistralai/Mixtral-8x7B-Instruct-v0.1 -q "$userInput" | glow
